name: Iroha2 dev send schema to client
on:
  push:
    branches: [iroha2-dev-schema-to-client]
jobs:
  dispatch:
#    runs-on: [ self-hosted, Linux ] TODO
    runs-on: ubuntu-latest
    container: rust:1.56-buster
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y --no-install-recommends \
          build-essential \
          ca-certificates \
          clang \
          llvm-dev
      - name: Build
        run: cargo build --release --verbose
      - name: Archive build
        uses: actions/upload-artifact@v2
        with:
          name: cargo-build-release
          path: target/release/iroha
      - name: Archive Client CLI build
        uses: actions/upload-artifact@v2
        with:
          name: cargo-client-cli-build-release
          path: target/release/iroha_client_cli
      - name: Archive Crypto CLI build
        uses: actions/upload-artifact@v2
        with:
          name: cargo-crypto-cli-build-release
          path: target/release/iroha_crypto_cli
      - name: Run schema generation
        run: |
          mkdir -p target/schema
          cargo run -p iroha_schema_bin > target/schema/schema.json
      - name: Upload schema
        uses: actions/upload-artifact@v2
        with:
          name: schema
          path: target/schema
      - name: Schema file hash
        run: echo "::set-output name=SCHEMA_FILE_HASH::$(sha256sum target/schema/schema.json | awk '{print $1}')"
        id: schema-hash
      - uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}
          repository: arndey/iroha-java
          event-type: update-schema
          client-payload: '{"schemaHash": "${{ steps.schema-hash.outputs.SCHEMA_FILE_HASH }}"}'